# Machine Learning Basics Using Scikit Learn

In [1]:
#import libraries
import numpy as np
import pandas as pd

In [2]:
#import scikit learn dataset
from sklearn.datasets import load_boston
boston_dataset = load_boston()

C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Ca

In [3]:
print(boston_dataset['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [4]:
#print features of dataset
print(boston_dataset['feature_names'])

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [5]:
#store data into df
df_boston = pd.DataFrame(boston_dataset.data)

In [6]:
df_boston.columns = boston_dataset.feature_names

In [7]:
#view first 5 observations of dataset
df_boston.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [10]:
#print dataset matrix (observations and features)
boston_dataset.data.shape

(506, 13)

In [11]:
#print dataset target shape (response)
boston_dataset.target.shape

(506,)

In [12]:
#view target or response
boston_dataset['target']

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

# Linear Regression Model Demo

In [13]:
#import libraries
import numpy as np
import pandas as pd

In [14]:
#import scikit learn dataset
from sklearn.datasets import load_boston
boston_dataset = load_boston()

C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Ca

In [15]:
#store data into df
df_boston = pd.DataFrame(boston_dataset.data)

In [16]:
df_boston.columns = boston_dataset.feature_names

In [17]:
#append price column as new target
df_boston['Price'] = boston_dataset.target

In [18]:
df_boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  Price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [19]:
#assign attributes to x-axis
X_features = boston_dataset.data

In [20]:
#assign target on Y axis
Y_target = boston_dataset.target

In [21]:
#import linear model - the estimator
from sklearn.linear_model import LinearRegression
lineReg = LinearRegression()

In [22]:
#fit data into estimator
lineReg.fit(X_features,Y_target)

LinearRegression()

In [23]:
#print the intercept
print('The estimated intercept %.2f' %lineReg.intercept_)

The estimated intercept 36.46


In [24]:
#print the coefficient
print('The coefficient is %d' %len(lineReg.coef_))

The coefficient is 13


In [26]:
#split dataset into train and test 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_features,Y_target)

In [28]:
#print the dataset shape
boston_dataset.data.shape

(506, 13)

In [29]:
#print shapes of training and test datasets
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(379, 13) (127, 13) (379,) (127,)


In [30]:
#fit the training set into the model
lineReg.fit(X_train,Y_train)

LinearRegression()

In [34]:
#calculate MSE (mean square error) for the model or residual sum of squares
print('MSE value is %.2f' %(np.mean(lineReg.predict(X_test)-Y_test) ** 2))

MSE value is 0.02


In [35]:
#calulate variance
print('Variance score is %.2f' %lineReg.score(X_test,Y_test))

Variance score is 0.76


# KNN Logistic Regression Model Example

In [36]:
#import libraries
import numpy as np
import pandas as pd

In [37]:
#import scikit learn dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [38]:
type(iris_dataset)

sklearn.utils.Bunch

In [41]:
print(iris_dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [42]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [43]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
iris_dataset.data.shape

(150, 4)

In [46]:
#assign attributes to x-axis
X_features = iris_dataset.data

In [47]:
#assign target on Y axis
Y_target = iris_dataset.target

In [49]:
print(X_features.shape)
print(Y_target.shape)

(150, 4)
(150,)


In [50]:
#first use KNN classifier method
from sklearn.neighbors import KNeighborsClassifier

In [52]:
#instantiate the KNN estimator
knn = KNeighborsClassifier(n_neighbors=1)

In [54]:
#print th knn
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [55]:
#fit data into knn model
knn.fit(X_features,Y_target)

KNeighborsClassifier(n_neighbors=1)

In [56]:
#create object with new set of values
X_new = [[3,5,4,1],[5,3,4,2]]

In [57]:
#predict the outcome for new observation using knn classifier
knn.predict(X_new)

array([1, 1])

In [58]:
#use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression()

In [59]:
#fit data into estimator
LogReg.fit(X_features,Y_target)

C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [60]:
#predict the outcome 
LogReg.predict(X_new)

array([0, 1])

# Unsupervised Learning: K-Means Clustering

In [1]:
import numpy as np

In [4]:
#import k-means class from sklearn cluster
from sklearn.cluster import KMeans

In [5]:
#import make_blobs dataset from sklearn cluster
from sklearn.datasets import make_blobs


In [6]:
#define no of samples
n_samples = 300

In [7]:
#define random state value to initialize the center
random_state = 20

In [8]:
#define no of feature as 5
X,y = make_blobs(n_samples=n_samples,n_features = 5, random_state= None)

In [9]:
#define no of clusters to be formed as 3 and in random state and fit features into the model
predict_y = KMeans(n_clusters = 3,random_state = random_state).fit_predict(X)

In [10]:
#print the estimator prediction
predict_y

array([2, 2, 0, 1, 1, 2, 1, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 2,
       1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 2,
       1, 2, 1, 0, 2, 2, 2, 2, 0, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 2, 2,
       1, 2, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 0, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 2, 0, 2,
       2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0,
       0, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0,
       0, 2, 0, 1, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2, 0, 1, 1, 2, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2,
       0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2,
       0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2,
       2, 2, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 0])

# Unsupervised Learning- PCA

In [2]:
from sklearn.decomposition import PCA

In [3]:
from sklearn.datasets import make_blobs

In [4]:
#define samples and random_state
n_sample = 20
random_state = 20

In [5]:
#generate the dataset with 10 features
X,y = make_blobs(n_samples = n_sample,n_features = 10,random_state = None)

In [7]:
#view shape of dataset
X.shape

(20, 10)

In [8]:
#define PCA estimator with no of reduced components
pca = PCA(n_components = 3)

In [10]:
#fit the data into model
pca.fit(X)
print(pca.explained_variance_ratio_)

[0.67253343 0.26608765 0.02018215]


In [11]:
#print first PCA component
first_pca = pca.components_[0]

In [12]:
print(first_pca)

[-0.22490849  0.18014596  0.37860598  0.17400511 -0.69772047 -0.20198914
 -0.07204105 -0.15850471  0.03503943 -0.42917182]


In [13]:
#transform the fitted data using transform method
pca_reduced = pca.transform(X)

In [14]:
#view the shape
pca_reduced.shape

(20, 3)

# Build ML Pipeline

In [15]:
#import pipeline class
from sklearn.pipeline import Pipeline

In [17]:
#import linear estimator
from sklearn.linear_model import LinearRegression

In [18]:
#import PCA estimator for dimentionality reduction
from sklearn.decomposition import PCA

In [19]:
#chain the estimators together
estimator = [('dim_reduction',PCA()),('linear_model',LinearRegression())]

In [20]:
#put the chain of estimators in pipeline object
pipeline_estimator = Pipeline(estimator)

In [21]:
#check the chain of estimators
pipeline_estimator

Pipeline(steps=[('dim_reduction', PCA()), ('linear_model', LinearRegression())])

In [22]:
#view first step
pipeline_estimator.steps[0]

('dim_reduction', PCA())

In [23]:
#view second step
pipeline_estimator.steps[1]

('linear_model', LinearRegression())

In [24]:
#view all the pipelines
pipeline_estimator.steps

[('dim_reduction', PCA()), ('linear_model', LinearRegression())]

# Model Persistance

In [25]:
# import required libraries and dataset
from sklearn.datasets import load_iris

In [26]:
iris_dataset = load_iris()

In [28]:
#view feature Names of dataset
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
#view target of dataset
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
#define features and target objects
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [31]:
#create objects for new values for prediction
X_new = [[3,5,4,1],[5,3,4,2]]

In [32]:
#use logistic regressor
from sklearn.linear_model import LogisticRegression

In [33]:
logReg = LogisticRegression()

In [35]:
#fit data into estimator
logReg.fit(X_feature,Y_target)

C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
#predict the outcome for new observation
logReg.predict(X_new)

array([0, 1])

In [37]:
#import library for model persistance
import pickle as pkl

In [38]:
#use dumps method to persist the model
persist_model = pkl.dumps(logReg)

In [39]:
persist_model

b'\x80\x04\x95\x03\x03\x00\x00\x00\x00\x00\x00\x8c\x1esklearn.linear_model._logistic\x94\x8c\x12LogisticRegression\x94\x93\x94)\x81\x94}\x94(\x8c\x07penalty\x94\x8c\x02l2\x94\x8c\x04dual\x94\x89\x8c\x03tol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\rfit_intercept\x94\x88\x8c\x11intercept_scaling\x94K\x01\x8c\x0cclass_weight\x94N\x8c\x0crandom_state\x94N\x8c\x06solver\x94\x8c\x05lbfgs\x94\x8c\x08max_iter\x94Kd\x8c\x0bmulti_class\x94\x8c\x04auto\x94\x8c\x07verbose\x94K\x00\x8c\nwarm_start\x94\x89\x8c\x06n_jobs\x94N\x8c\x08l1_ratio\x94N\x8c\x0en_features_in_\x94K\x04\x8c\x08classes_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x1c\x8c\x05dtype\x94\x93\x94\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x0c\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x94t\x94b\x8c\x07n_iter_\x9

In [41]:
#use joblib.dump to persist the model to a file
import joblib

In [42]:
joblib.dump(logReg,'regresfilename.pkl')

['regresfilename.pkl']

In [44]:
#use joblib.load to persist model to a file
new_logreg_estimator = joblib.load('regresfilename.pkl')

In [45]:
new_logreg_estimator

LogisticRegression()

In [46]:
#validate and use new estimator object to predict
new_logreg_estimator.predict(X_new)

array([0, 1])