# Scipy Integrations

In [1]:
from scipy.integrate import quad

In [2]:
def integrate_function(x):
    return x

In [3]:
quad(integrate_function,0,1)

(0.5, 5.551115123125783e-15)

In [4]:
def int_func(x,a,b):
    return a*x+b

In [5]:
a = 3
b = 2

In [6]:
quad(int_func,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [8]:
from scipy import integrate

In [9]:
def f(x,y):
    return x+y

In [10]:
integrate.dblquad(f,0,1,lambda x:0 , lambda x: 2)

(3.0, 4.436070580899685e-14)

# Scipy Optimizations

In [12]:
import numpy as np
from scipy import optimize

In [13]:
def f(x):
    return x*x + 5 *np.sin(x)

In [14]:
minima_value = optimize.minimize(f,x0=2,method = 'bfgs',options = {'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [15]:
minimavaluewithoutopt = optimize.minimize(f,x0=2,method = 'bfgs')
minimavaluewithoutopt

      fun: -3.2463942726915196
 hess_inv: array([[0.15445831]])
      jac: array([-4.47034836e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

# Inverse Matrix

In [19]:
mat = np.array([[3,7],[2,2]])

In [20]:
from scipy import linalg
linalg.inv(mat)

array([[-0.25 ,  0.875],
       [ 0.25 , -0.375]])

# Determinant of Matrix

In [23]:
linalg.det(mat)

-8.0

# Solve Linear Equation

In [25]:
#2x+3y+z = 21
#-x+5y+4z = 9
#3x+2y+9z = 14

In [27]:
numarr = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [28]:
numarrValue = np.array([21,9,14])

In [29]:
linalg.solve(numarr,numarrValue)

array([ 5.41666667,  3.75      , -1.08333333])

In [30]:
#singlular Value Decomposition(SVD)
linalg.svd(numarr)

(array([[-0.2344097 , -0.33590599, -0.91226052],
        [-0.48608065, -0.77217819,  0.40922663],
        [-0.84188936,  0.53935888,  0.01772866]]),
 array([11.16574895,  4.40001239,  2.44252764]),
 array([[-0.22465191, -0.43144541, -0.87371985],
        [ 0.39055409, -0.86133648,  0.32491072],
        [-0.89274802, -0.26824305,  0.36200365]]))

# Eigen Values and Eigen Vectors

In [32]:
import numpy as np
from scipy import linalg

In [33]:
test_rating_data = np.array([[2,3],[3,8]])

In [34]:
eigenValues,eigenVectors = linalg.eig(test_rating_data)

In [37]:
first_eigen ,second_eigen = eigenValues

In [38]:
first_eigen

(0.7573593128807152+0j)

In [39]:
second_eigen

(9.242640687119286+0j)

In [41]:
#first Eigen vector
eigenVectors[:,0]

array([-0.92387953,  0.38268343])

In [42]:
#second Eigen vector
eigenVectors[:,1]

array([-0.38268343, -0.92387953])

# Scipy Statistics

In [44]:
from scipy.stats import norm

In [45]:
#random variables
norm.rvs(loc =0,scale = 1,size = 10)

array([ 1.14429567,  0.67072942, -0.65687886,  2.06787919, -0.02462862,
        0.28562382, -0.40050503, -1.26532374, -0.52906541, -0.78010028])

In [46]:
norm.cdf(5,loc =1,scale =2)

0.9772498680518208

In [48]:
norm.pdf(9,loc =0,scale =1)

1.0279773571668917e-18