# Numpy Data Analysis Basics

In [1]:
import numpy as np

# Create a 1D array

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
# check the array

print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
# Check the shape of the array

print(arr1.shape)

(3,)


In [4]:
# accessing elements from the array

arr1[2]

3

In [5]:
# Change an element from the array

arr1[2]= 5

In [6]:
arr1

array([1, 2, 5])

In [7]:
# Create a 2D array

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
# Check the shape of the array

print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [9]:
# Accessing elements from the array

arr2[0][2]

3

In [10]:
arr2[0,2]

3

In [11]:
arr2[0,-2]

2

In [12]:
arr2[0,-1]

3

In [13]:
arr2[-1, 0]

4

In [14]:
# Array of type string

arr3 = np.array(['India', 'China', 'USA' , 'Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [15]:
arr3[1]

'China'

In [16]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
# Array of evenly spaced number in a specified interval

arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [18]:
# Array of random values between 0 and 1 in a given shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.76609137 0.90660162 0.4595946  0.09276739 0.43626907 0.5748815
 0.06022887 0.08741953 0.909074   0.20805301]


[[0.75247591 0.25365498 0.12523213 0.08417047]
 [0.42934556 0.10407552 0.68913867 0.93354129]
 [0.6176221  0.58276089 0.87532998 0.00866804]]


In [19]:
# Array of zeros

print(np.zeros(10))
print('\n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [22]:
# Create an array by repetition
# epeat each element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2]


In [23]:
# Repeat an array by a specified number of times

arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [24]:
# Create an idenity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Create a matrix with a specified diagonal array

arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
arr = np.random.rand(5,5)
print(arr)

[[0.49594371 0.21768502 0.69476238 0.00741987 0.44744084]
 [0.69712512 0.84548515 0.14865689 0.41753281 0.3233278 ]
 [0.69160897 0.89807677 0.25541268 0.61187713 0.73491297]
 [0.5319836  0.3767479  0.91006091 0.99483816 0.7919427 ]
 [0.39689397 0.46351014 0.79795882 0.53139965 0.33023608]]


In [28]:
# Extract the diagonal elements in the array
print(np.diag(arr))

[0.49594371 0.84548515 0.25541268 0.99483816 0.33023608]


In [29]:
# Display the length of the array
print(len(arr))

5


In [30]:
# Display the dimension of the array
print(arr.ndim)

2


In [31]:
# Display the size of the elements
print(arr.size)

25


In [32]:
# print 4 random integers

print(np.random.randint(-10, 10, 4))

[  3   6   1 -10]


In [33]:
# Mathematical operations

print(arr + 10)
print('\n')
print(arr - 10)
print('\n')
print(arr * 10)
print('\n')
print(arr / 10)

[[10.49594371 10.21768502 10.69476238 10.00741987 10.44744084]
 [10.69712512 10.84548515 10.14865689 10.41753281 10.3233278 ]
 [10.69160897 10.89807677 10.25541268 10.61187713 10.73491297]
 [10.5319836  10.3767479  10.91006091 10.99483816 10.7919427 ]
 [10.39689397 10.46351014 10.79795882 10.53139965 10.33023608]]


[[-9.50405629 -9.78231498 -9.30523762 -9.99258013 -9.55255916]
 [-9.30287488 -9.15451485 -9.85134311 -9.58246719 -9.6766722 ]
 [-9.30839103 -9.10192323 -9.74458732 -9.38812287 -9.26508703]
 [-9.4680164  -9.6232521  -9.08993909 -9.00516184 -9.2080573 ]
 [-9.60310603 -9.53648986 -9.20204118 -9.46860035 -9.66976392]]


[[4.95943714 2.17685022 6.94762379 0.07419865 4.47440841]
 [6.97125122 8.45485148 1.48656888 4.17532815 3.23327798]
 [6.91608966 8.98076765 2.55412676 6.11877127 7.34912965]
 [5.31983604 3.76747899 9.10060913 9.94838164 7.91942699]
 [3.96893973 4.63510142 7.97958816 5.31399647 3.30236085]]


[[0.04959437 0.0217685  0.06947624 0.00074199 0.04474408]
 [0.06971251 

In [34]:
# Exponentiation

print(np.exp(arr))

[[1.64204713 1.24319543 2.00323301 1.00744746 1.56430376]
 [2.00797173 2.3291075  1.16027482 1.51821122 1.3817182 ]
 [1.99692594 2.45487726 1.29099427 1.84388937 2.08530049]
 [1.70230566 1.45753682 2.48447386 2.70428665 2.20768112]
 [1.48719824 1.58964408 2.22100282 1.70131188 1.39129655]]


In [35]:
# Natural logarithm

print(np.log(arr))

[[-0.70129284 -1.52470611 -0.36418539 -4.90359436 -0.80421095]
 [-0.36079037 -0.16784468 -1.90611439 -0.87339214 -1.12908862]
 [-0.36873456 -0.10749973 -1.36487471 -0.49122379 -0.3080032 ]
 [-0.63114261 -0.97617902 -0.09424374 -0.0051752  -0.23326624]
 [-0.92408611 -0.76892701 -0.22569829 -0.63224091 -1.10794747]]


In [36]:
# Base 2 logarithm

print(np.log2(arr))

[[-1.0117517  -2.19968595 -0.52540846 -7.07439126 -1.16023115]
 [-0.52051048 -0.24214868 -2.74994178 -1.26003851 -1.62893055]
 [-0.53197152 -0.15508933 -1.96909797 -0.70868613 -0.44435469]
 [-0.91054631 -1.40832863 -0.13596498 -0.00746624 -0.33653205]
 [-1.33317444 -1.10932719 -0.32561381 -0.91213082 -1.59843032]]


In [37]:
# Base 10 logarithm

print(np.log10(arr))

[[-0.30456761 -0.66217145 -0.15816371 -2.12960397 -0.34926438]
 [-0.15668927 -0.07289402 -0.82781496 -0.37930939 -0.49035696]
 [-0.16013939 -0.04668654 -0.59275755 -0.21333578 -0.13376409]
 [-0.27410175 -0.42394916 -0.04092954 -0.00224756 -0.10130624]
 [-0.4013255  -0.33394076 -0.09801952 -0.27457874 -0.48117547]]


In [38]:
# sin function

print(np.sin(arr))

[[0.47586188 0.21596986 0.64020292 0.0074198  0.43265972]
 [0.6420162  0.74829303 0.14810997 0.40550645 0.31772368]
 [0.63777727 0.78212996 0.25264472 0.57440503 0.67052259]
 [0.50724381 0.3678984  0.78954112 0.83867083 0.71171929]
 [0.38655563 0.44709064 0.71593249 0.50674047 0.32426637]]


In [39]:
print(np.sin(180))

-0.8011526357338304


In [40]:
print(np.sin(0))

0.0


In [41]:
# cos function

print(np.cos(arr))

[[0.87952002 0.97640003 0.76820585 0.99997247 0.9015573 ]
 [0.76669107 0.66336833 0.9889709  0.91409218 0.94818335]
 [0.77022085 0.62311534 0.96755912 0.81857123 0.74188912]
 [0.8618026  0.92986599 0.61369766 0.54463862 0.70246399]
 [0.92226609 0.89448866 0.69816951 0.86209866 0.94596582]]


In [42]:
print(arr)

[[0.49594371 0.21768502 0.69476238 0.00741987 0.44744084]
 [0.69712512 0.84548515 0.14865689 0.41753281 0.3233278 ]
 [0.69160897 0.89807677 0.25541268 0.61187713 0.73491297]
 [0.5319836  0.3767479  0.91006091 0.99483816 0.7919427 ]
 [0.39689397 0.46351014 0.79795882 0.53139965 0.33023608]]


In [43]:
# sum along the row
print(np.sum(arr, axis=0))

[2.81355538 2.80150498 2.80685167 2.56306762 2.62786039]


In [44]:
# sum along the column
print(np.sum(arr, axis=1))

[1.86325182 2.43212777 3.1918885  3.60557328 2.51999866]


In [45]:
# minimum item value along the row
print(np.min(arr))

0.007419865441084861


In [46]:
print(np.max(arr))

0.994838163773579


In [47]:
# calculate the overall mean

print(np.mean(arr))

0.5445136013098181


In [48]:
# calculate the mean along the row

print(np.mean(arr, axis=0))

[0.56271108 0.560301   0.56137033 0.51261352 0.52557208]


In [49]:
# calculate the median
print(np.median(arr))

0.5313996474815373


In [50]:
# calculate the standard deviation
print(np.std(arr))

0.2530529937952706


In [51]:
# calculate the variance
print(np.var(arr))

0.06403581766874926


In [52]:
print(arr)
print('\n')
print(arr[1:3, 2:5])

[[0.49594371 0.21768502 0.69476238 0.00741987 0.44744084]
 [0.69712512 0.84548515 0.14865689 0.41753281 0.3233278 ]
 [0.69160897 0.89807677 0.25541268 0.61187713 0.73491297]
 [0.5319836  0.3767479  0.91006091 0.99483816 0.7919427 ]
 [0.39689397 0.46351014 0.79795882 0.53139965 0.33023608]]


[[0.14865689 0.41753281 0.3233278 ]
 [0.25541268 0.61187713 0.73491297]]


In [53]:
# Sort an array
arr = np.random.rand(5,5)
print(arr)

[[0.68751282 0.85769013 0.66237078 0.6133892  0.74190493]
 [0.18152674 0.58039301 0.56061448 0.29762193 0.90494967]
 [0.71943995 0.17396257 0.99490009 0.63948619 0.88627087]
 [0.795357   0.09324764 0.86996225 0.91528843 0.32231884]
 [0.97149297 0.76163771 0.56337065 0.87601076 0.02286082]]


In [54]:
# sort along the column

print(np.sort(arr, axis=1))

[[0.6133892  0.66237078 0.68751282 0.74190493 0.85769013]
 [0.18152674 0.29762193 0.56061448 0.58039301 0.90494967]
 [0.17396257 0.63948619 0.71943995 0.88627087 0.99490009]
 [0.09324764 0.32231884 0.795357   0.86996225 0.91528843]
 [0.02286082 0.56337065 0.76163771 0.87601076 0.97149297]]


In [55]:
# Transpose an array
print(arr)
print('\n')
print(arr.T)

[[0.68751282 0.85769013 0.66237078 0.6133892  0.74190493]
 [0.18152674 0.58039301 0.56061448 0.29762193 0.90494967]
 [0.71943995 0.17396257 0.99490009 0.63948619 0.88627087]
 [0.795357   0.09324764 0.86996225 0.91528843 0.32231884]
 [0.97149297 0.76163771 0.56337065 0.87601076 0.02286082]]


[[0.68751282 0.18152674 0.71943995 0.795357   0.97149297]
 [0.85769013 0.58039301 0.17396257 0.09324764 0.76163771]
 [0.66237078 0.56061448 0.99490009 0.86996225 0.56337065]
 [0.6133892  0.29762193 0.63948619 0.91528843 0.87601076]
 [0.74190493 0.90494967 0.88627087 0.32231884 0.02286082]]


In [56]:
print(arr.transpose())

[[0.68751282 0.18152674 0.71943995 0.795357   0.97149297]
 [0.85769013 0.58039301 0.17396257 0.09324764 0.76163771]
 [0.66237078 0.56061448 0.99490009 0.86996225 0.56337065]
 [0.6133892  0.29762193 0.63948619 0.91528843 0.87601076]
 [0.74190493 0.90494967 0.88627087 0.32231884 0.02286082]]


In [57]:
# Flatten the 2D array

print(arr)
print('\n')
print(arr.flatten())

[[0.68751282 0.85769013 0.66237078 0.6133892  0.74190493]
 [0.18152674 0.58039301 0.56061448 0.29762193 0.90494967]
 [0.71943995 0.17396257 0.99490009 0.63948619 0.88627087]
 [0.795357   0.09324764 0.86996225 0.91528843 0.32231884]
 [0.97149297 0.76163771 0.56337065 0.87601076 0.02286082]]


[0.68751282 0.85769013 0.66237078 0.6133892  0.74190493 0.18152674
 0.58039301 0.56061448 0.29762193 0.90494967 0.71943995 0.17396257
 0.99490009 0.63948619 0.88627087 0.795357   0.09324764 0.86996225
 0.91528843 0.32231884 0.97149297 0.76163771 0.56337065 0.87601076
 0.02286082]


In [58]:
# Append elements to an array

arr = np.array([4,5,6,7])

In [59]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [60]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [61]:
# Insert elements to an array

arr3 = np.insert(arr, 0, [12,13,14])
print(arr3)

[12 13 14  4  5  6  7]


In [62]:
# Remove elements from an array

print(arr)
print('\n')
arr4 = np.delete(arr, 0)
print(arr4)

[4 5 6 7]


[5 6 7]


In [63]:
# Delete multiple elements

print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [64]:
# Copy elements from an array

arr1 = np.arange(10, 40, 3)
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [65]:
arr_copy = np.copy(arr1)
arr_copy

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [66]:
arr_copy = arr1.copy()
print(arr_copy)

[10 13 16 19 22 25 28 31 34 37]


In [67]:
# Combine and split an array

arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [68]:
# Combine the array items by row

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [69]:
# Combine array items by column

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [70]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [71]:
# Stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [72]:
# Set operations

# Find elements from an array
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [73]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [74]:
# Intersection of 2 array elements

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [75]:
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [76]:
# Union of 2 array elements

print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [77]:
# Elements present in first array but not in the second array
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2]
[6 7]


In [78]:
# Elements present in either of the arrays but not both

print(np.setxor1d(arr1, arr2))

[1 2 6 7]
