In [1]:
import numpy as np

In [2]:
first_numpy_array = np.array([1,2,3,40])

In [3]:
first_numpy_array

array([ 1,  2,  3, 40])

In [4]:
zeros_array = np.zeros((3,3))

In [5]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones_array = np.ones((3,3))

In [7]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
empty_array = np.empty((3,3))

In [9]:
empty_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arange_array = np.arange(12)
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arange_array.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
linspaced = np.linspace(1,6,3)

In [14]:
linspaced

array([1. , 3.5, 6. ])

In [15]:
ThreeD_array = np.arange(27).reshape(3,3,3)

In [16]:
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
np.add(45,20)

65

In [18]:
np.subtract(23,4)

19

In [19]:
np.daily_earning = np.array([7,6,5,9,3,4,5])*15

In [20]:
np.daily_earning

array([105,  90,  75, 135,  45,  60,  75])

In [21]:
sum(np.daily_earning)

585

In [22]:
weekly_hrs = np.array([34,43,45,47,38])

In [23]:
weekly_hrs[weekly_hrs<40]

array([34, 38])

In [24]:
#Logical operators
np.logical_and(weekly_hrs>35,weekly_hrs<45)

array([False,  True, False, False,  True])

In [25]:
np_sqrt = np.sqrt([2,3,4,5])

In [26]:
np_sqrt

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [27]:
from numpy import pi

In [28]:
np.sin(pi/2)

1.0

In [33]:
#shape Manipulation

In [36]:
data_array = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11]])

In [37]:
data_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
data_array.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
data_array.resize(3,4)

In [41]:
data_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
np.hsplit(data_array,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [44]:
np.hstack((zeros_array,ones_array))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [45]:
data_array.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
square = np.array([[23,45],[23,44]])

In [48]:
square

array([[23, 45],
       [23, 44]])

In [49]:
#inverse of matrix
np.linalg.inv(square)

array([[-1.91304348,  1.95652174],
       [ 1.        , -1.        ]])

In [50]:
np.trace(square)

67