# Numpy

In [1]:
# Numpy - Numerical Python 
#The core object- array (array-list of elements)
import numpy as np #np is an alias for numpy

In [2]:
list1=[1,2,3,4,5,6]
list1

[1, 2, 3, 4, 5, 6]

In [3]:
#one-dimensional array
#transform a list into array
oneDimExample=np.array(list1)
oneDimExample

array([1, 2, 3, 4, 5, 6])

In [4]:
type(oneDimExample)

numpy.ndarray

In [5]:
#numpy could be 1-dim, 2-dim, ...,n-dim

In [6]:
#displays the number of dimensions
oneDimExample.ndim

1

In [7]:
oneDimExample

array([1, 2, 3, 4, 5, 6])

In [8]:
#shape- no of columns and rows
oneDimExample.shape

(6,)

In [9]:
#size - total no of elements 
oneDimExample.size

6

In [10]:
#sum of elements
oneDimExample.sum()

21

In [11]:
oneDimExample[1]#- one-dim

2

In [12]:
#nested list
list2=[[1,2,3],[4,5,6],[7,8,9]]
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
len(list2)

3

In [14]:
list2[1][1]

5

In [15]:
twoDimExample=np.array(list2) #2-dim array
twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
twoDimExample.ndim

2

In [17]:
twoDimExample.shape

(3, 3)

In [18]:
twoDimExample.size

9

In [19]:
#difference between Matrix and Array
# np.matrix()
# np.array()

In [20]:
#Array and Matrix
twoDimArray=np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
twoDimMatrix=np.matrix([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

In [21]:
print(type(twoDimArray))
print(type(twoDimMatrix))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [22]:
#perform multiplication of the array - element-wise multiplication
# 1 2 3       1 2 3       (1*1) (2*2) (3*3)
# 4 5 6 *     4 5 6 =     (4*4) (5*5) (6*6)
# 7 8 9       7 8 9       (7*7) (8*8) (9*9)

In [23]:
twoDimArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
resultArray=twoDimArray*twoDimArray
resultArray

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
resultMatrix=twoDimMatrix*twoDimMatrix
resultMatrix

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [26]:
#Numpy array operations
#Arithmetic operators: +,-,*,/,%,**

In [27]:
resultAddition=twoDimArray+twoDimArray
resultAddition

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
twoDimArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#raise to the power
Pwr_2=twoDimArray**2
Pwr_2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [30]:
add2=twoDimArray+2
add2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
#arange -array range
# np.arange(start_value,upperbound,step_size)
a1=np.arange(0,11,2)
a1

array([ 0,  2,  4,  6,  8, 10])

In [32]:
a1.ndim

1

In [33]:
#zero and ones array
#zero array - creates a zero array with a specific no of elements
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
a2=np.zeros((4,4))
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
#linspace - returns evenly spaced numbers (3 numbers in our case) over a specified interval (in our case between 0 and 10)
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [37]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [38]:
#Generate random numbers
# rand -returns uniform distribution data - range(0,1)
np.random.rand(10)

array([0.61035469, 0.25556296, 0.69455465, 0.91503074, 0.86087315,
       0.5183921 , 0.65526308, 0.27809377, 0.10014971, 0.89197346])

In [39]:
#randn- returns Normal distribution data - mean=0; std dev=1
data=np.random.randn(100)
print(np.mean(data))
print(np.std(data))

0.1471166415203733
1.0452262869185165


In [40]:
#randint(startrange,endrange,no of elem)
data=np.random.randint(1,100,9)

In [41]:
data

array([20, 27, 75, 96, 26, 77, 69, 97, 64])

In [42]:
# Other functions
array1=np.array([4,2,900,5,2,78,9,900,234,567,2,1])

In [43]:
array1.max() #- maximum value in the array

900

In [44]:
array1.argmax() #- index location of the maximum value

2

In [45]:
data.size

9

In [46]:
#changing the dimension of an array
#reshape - allows you to convert 1d to 2d
#product of the no of rows and no of columns it has to be equal with the total no of elements of the array
#possible combinations for our ex: (3,3); (9,1); (1,9)
data2=data.reshape(3,3)
data2

array([[20, 27, 75],
       [96, 26, 77],
       [69, 97, 64]])

In [47]:
data3=np.array([4,2,900,5,2,78,9,900,234,567,2,1])
data3.size

12

In [48]:
data4=data3.reshape(3,4)

In [49]:
data4

array([[  4,   2, 900,   5],
       [  2,  78,   9, 900],
       [234, 567,   2,   1]])

In [50]:
data2

array([[20, 27, 75],
       [96, 26, 77],
       [69, 97, 64]])

In [51]:
#ravel - flattens the array - convert a 2D array in 1D array
data2.ravel()

array([20, 27, 75, 96, 26, 77, 69, 97, 64])

In [52]:
#Numpy- subsetting
data1=np.random.randint(1,100,9)
data1

array([ 9, 58, 46, 58, 41, 28, 51,  4, 92])

In [53]:
data1[-1] #or data1[8] 

92

In [54]:
data1[1:6]

array([58, 46, 58, 41, 28])

In [55]:
#extract from 2 dim array
data2

array([[20, 27, 75],
       [96, 26, 77],
       [69, 97, 64]])

In [56]:
#second row, second column
data2[1][1] #or data2[1,1] 

26

In [57]:
data2[1][1:]

array([26, 77])

In [58]:
data2[1,1:3]

array([26, 77])

In [59]:
data2[0:2,1:3]

array([[27, 75],
       [26, 77]])

In [60]:
#Searching elements
data=np.array([[196,181,4],[142,185,30],[113,38,81]])

In [61]:
data==30

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [62]:
a=data>100
a

array([[ True,  True, False],
       [ True,  True, False],
       [ True, False, False]])

In [64]:
#return elements between 100 and 150
data[(data>100)&(data<150)]

array([142, 113])

In [65]:
np.sqrt(data)

array([[14.        , 13.45362405,  2.        ],
       [11.91637529, 13.60147051,  5.47722558],
       [10.63014581,  6.164414  ,  9.        ]])

In [66]:
np.sin(data) # np.cos(data) , np.exp(data), np.log(data)

array([[ 0.93953006, -0.9364514 , -0.7568025 ],
       [-0.58779501,  0.34662118, -0.98803162],
       [-0.09718191,  0.29636858, -0.62988799]])

In [67]:
#perform operations along a particular axis
data2

array([[20, 27, 75],
       [96, 26, 77],
       [69, 97, 64]])

In [68]:
data2.sum() # the sum of all the elements

551

In [70]:
data2.sum(axis=0) # gives the sum of the elements column wise

array([185, 150, 216])

In [71]:
data2.sum(axis=1) # gives the sum of the elements row wise

array([122, 199, 230])

In [72]:
# Datetime functions

In [74]:
#count the no of business days
np.busday_count('2021','2022',weekmask='1111100',holidays=['2021-01-01','2021-12-24','2021-12-25'])

259

In [75]:
import datetime

In [76]:
import dateutil

In [78]:
created_date=datetime.datetime(2015,12,31,23,59,45)
created_date

datetime.datetime(2015, 12, 31, 23, 59, 45)

In [79]:
closed_date=datetime.datetime(2016,1,1,12,55,0)
closed_date

datetime.datetime(2016, 1, 1, 12, 55)

In [80]:
request_closing_time=dateutil.relativedelta.relativedelta(closed_date,created_date)

In [81]:
request_closing_time


relativedelta(hours=+12, minutes=+55, seconds=+15)